version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0