const LoggingService = require('./logs/LoggingService'),
    VersionCheckHelper = require('./VersionCheckHelper'),
    CONSTANTS = require('./constants'),
    RedisGateway = require('./RedisGateway'),
    Bootstrap = require('./bootstrap'),
    HealthDao = require('./health/HealthDao'),
    RedisPoolFactory = require('./RedisPoolFactory'),
    DatabasePoolFactory = require('./DatabasePoolFactory'),
    AzureServiceBusGateway = require('./AzureServiceBusGateway'),
    BranchIoService = require('./BranchIoService'),
    AzureStorageAccountGateway = require('./AzureStorageAccountGateway'),
    SessionService = require('./SessionService'),
    AuditEventsReportsDao = require('./audit/AuditEventsReportsDao'),
    AttachmentsDao = require('./updates/AttachmentsDao'),
    AuditEventsDao = require('./audit/AuditEventsDao'),
    CsvHelper = require('./CsvHelper'),
    MediaService = require('./MediaService'),
    EncounterDao = require('./patient/EncounterDao'),
    UserDao = require('./user/UserDao'),
    AzureNotificationHubGateway = require('./AzureNotificationHubGateway'),
    PatientDao = require('./patient/PatientDao'),
    FamilyIdentityDao = require('./family/FamilyIdentityDao'),
    GQLResponseHelper = require('./GQLResponseHelper'),
    DaoHelper = require('./DaoHelper'),
    TenantSettingsDao = require('./tenant/TenantSettingsDao'),
    UserPatientMappingDao = require('./patient/UserPatientMappingDao'),
    DeviceInfoDao = require('./device/DeviceInfoDao'),
    SecurityService = require('./SecurityService'),
    DeviceHelper = require('./DeviceHelper'),
    UpdatesDao = require('./updates/UpdatesDao'),
    LocationSettingsDao = require('./location/LocationSettingsDao'),
    EntitiesFactory = require('./EntitiesFactory'),
    LocationDao = require('./location/LocationDao'),
    ZenithService = require('./ZenithService'),
    Errors = require('./custom-errors'),
    FamilyInvitationHelper = require('./FamilyInvitationHelper'),
    LocaleHelper = require('./LocaleHelper'),
    UpdatesService = require('./UpdatesService'),
    QuickMessagesDao = require('./quick-message/QuickMessagesDao'),
    ValidationService = require('./ValidationService'),
    translateText = require('./TranslationService'),
    graphQLSchema = require('./schema'),
    FixedContentDao = require('./fixed-contents/FixedContentDao'),
    AuditEventsHelper = require('./AuditEventsHelper'),
    PatientHelper = require('./patient/PatientHelper'),
    UserCacheHelper = require('./user/UserCacheHelper'),
    UpdatesHelper = require('./updates/UpdatesHelper'),
    CDRHelper = require('./CDRHelper'),
    EnvironmentHelper = require('./EnvironmentHelper'),
    UserAuthorizationHelper = require('./user/UserAuthorizationHelper'),
    FamilyMemberHelper = require('./FamilyMemberHelper'),
    RabbitMQPoolFactory = require('./csa/RabbitMQPoolFactory'),
    RabbitMQGateway = require('./csa/RabbitMQGateway'),
    TenantCsaCredentialDao = require('./tenant/TenantCsaCredentialDao'),
    TenantCsaRmqConfigurationDao = require('./tenant/TenantCsaRmqConfigurationDao'),
    TenantCsaDao = require('./tenant/TenantCsaDao'),
    HttpPoolFactory = require('./HttpPoolFactory'),
    DhpHttpGateway = require('./DhpHttpGateway'),
    {csaQueries} = require('./csa/graphql/GraphQLFileHelper'),
    CsaHttpGateway = require('./csa/CsaHttpGateway'),
    AzurePubSubClient = require('./pubsub/AzurePubSubClient'),
    ChatUpdatePublisher = require('./pubsub/ChatUpdatePublisher'),
    PublisherHelper = require('./pubsub/PublisherHelper'),
    RedisHelper = require('./pubsub/RedisHelper'),
    ChatDao = require('./chat/ChatDao'),
    ChatHelper = require('./chat/ChatHelper'),
    TenantHelper = require('./tenant/TenantHelper'),
    RedisTestHelper = require('./test/RedisTestHelper'),
    ReadReceiptsUpdatePublisher = require('./pubsub/ReadReceiptsUpdatePublisher'),
    PubSubUtils = require('./pubsub/utils');

module.exports = {
    ...LoggingService,
    ...VersionCheckHelper,
    ...RedisGateway,
    ...Bootstrap,
    ...HealthDao,
    ...RedisPoolFactory,
    ...DatabasePoolFactory,
    ...AzureServiceBusGateway,
    ...BranchIoService,
    ...AzureStorageAccountGateway,
    ...SessionService,
    ...AttachmentsDao,
    ...AuditEventsReportsDao,
    ...AuditEventsDao,
    ...CsvHelper,
    ...MediaService,
    ...EncounterDao,
    ...UserDao,
    ...AzureNotificationHubGateway,
    ...PatientDao,
    ...FamilyIdentityDao,
    ...GQLResponseHelper,
    ...DaoHelper,
    ...TenantSettingsDao,
    ...UserPatientMappingDao,
    ...DeviceInfoDao,
    ...SecurityService,
    ...DeviceHelper,
    ...UpdatesDao,
    ...LocationSettingsDao,
    ...EntitiesFactory,
    ...LocationDao,
    ...ZenithService,
    ...Errors,
    ...FamilyInvitationHelper,
    ...LocaleHelper,
    ...UpdatesService,
    ...QuickMessagesDao,
    ...ValidationService,
    translateText,
    ...AuditEventsHelper,
    ...PatientHelper,
    ...FixedContentDao,
    ...UserCacheHelper,
    ...UpdatesHelper,
    ...CDRHelper,
    ...EnvironmentHelper,
    ...UserAuthorizationHelper,
    ...FamilyMemberHelper,
    ...RabbitMQPoolFactory,
    ...RabbitMQGateway,
    ...TenantCsaCredentialDao,
    ...TenantCsaRmqConfigurationDao,
    ...TenantCsaDao,
    ...HttpPoolFactory,
    ...DhpHttpGateway,
    ...CsaHttpGateway,
    ...AzurePubSubClient,
    ...ChatUpdatePublisher,
    ...PublisherHelper,
    ...RedisHelper,
    ...ChatDao,
    ...ChatHelper,
    ...TenantHelper,
    ...RedisTestHelper,
    ...ReadReceiptsUpdatePublisher,
    ...PubSubUtils,
    csaQueries,
    CONSTANTS,
    graphQLSchema
};
