const DBError = require('./db-error'),
    ServiceError = require('./service-error'),
    TimeoutError = require('./timeout-error'),
    UnauthorizedError = require('./unauthorized-error'),
    NotUniqueError = require('./not-unique-error'),
    NotFoundError = require('./not-found'),
    TenantError = require('./tenant-error'),
    TenantRoleError = require('./tenant-role-error'),
    ValidationError = require('./validation-error'),
    VersionMismatchError = require('./version-mismatch-error'),
    UnsupportedVersionError = require('./unsupported-version-error'),
    PermissionError = require('./permission-error'),
    MediaDisabledError = require('./media-disabled-error'),
    TooManyRequestsError = require('./too-many-requests-error'),
    UserInputError = require('./user-input-error'),
    ForbiddenError = require('./forbidden-error'),
    AuthenticationError = require('./authentication-error'),
    DuplicatePatientUserError = require('./duplicate-patient-user-error'),
    InvalidFamilyTypeError = require('./invalid-family-type-error'),
    ChatDisabledError = require('./chat-disabled-error'),
    CSAError = require('./csa-error');

module.exports = {
    DBError,
    ServiceError,
    TimeoutError,
    NotUniqueError,
    UnauthorizedError,
    TenantError,
    TenantRoleError,
    NotFoundError,
    ValidationError,
    VersionMismatchError,
    UnsupportedVersionError,
    PermissionError,
    MediaDisabledError,
    TooManyRequestsError,
    UserInputError,
    ForbiddenError,
    AuthenticationError,
    DuplicatePatientUserError,
    InvalidFamilyTypeError,
    ChatDisabledError,
    CSAError
};
