name: CI - EULA/PRIVACY/VERSIONED
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to customize ({major}.{minor}.{patch}-build.{buildnumber}, eg: 1.0.0-build.93)"
        required: true
      lastSupportedVersion:
        description: "Last supported client version ({major}.{minor}.{patch}, eg: 1.0.0) - empty field = ignored, required for versioned workflows"
      serverVersion:
        description: "Target server version ({major}.{minor}.{patch}, eg: 1.3.0) - empty field = ignored, required for versioned workflows"
      eulacg:
        description: "EULA text for caregiver as a string - empty field = ignored"
      eulafm:
        description: "EULA text for family member as a string - empty field = ignored"
      privacycg:
        description: "Privacy text for caregiver as a string - empty field = ignored"
      privacyfm:
        description: "Privacy text for family member as a string - empty field = ignored"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Azure login"
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build dockerfile"
        run: |
          echo "FROM vltprodusacr.azurecr.io/ohana-app-service-api:${{ github.event.inputs.version }}" > dockerfile
          if [ ! -z "${{ github.event.inputs.privacycg }}" ]; then echo "RUN echo \"${{ github.event.inputs.privacycg }}\" > ./fastify-api/config/caregiver-privacy-notice.txt" >> dockerfile; fi
          if [ ! -z "${{ github.event.inputs.privacyfm }}" ]; then echo "RUN echo \"${{ github.event.inputs.privacyfm }}\" > ./fastify-api/config/family-member-privacy-notice.txt" >> dockerfile; fi

          if [ ! -z "${{ github.event.inputs.eulacg }}" ]
            then 
              echo "RUN echo \"${{ github.event.inputs.eulacg }}\" > ./fastify-api/config/caregiver-eula.txt" >> dockerfile
              echo "RUN sed -i \"s|CAREGIVER_EULA_LAST_CHANGED_DATE: '[0-9]\{4\}-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]\.[0-9]\{3\}Z'|CAREGIVER_EULA_LAST_CHANGED_DATE: '$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")'|\" ./shared/constants.js" >> dockerfile
            fi

          if [ ! -z "${{ github.event.inputs.eulafm }}" ]
            then
              echo "RUN echo \"${{ github.event.inputs.eulafm }}\" > ./fastify-api/config/family-member-eula.txt" >> dockerfile
              echo "RUN sed -i \"s|FAMILY_MEMBER_EULA_LAST_CHANGED_DATE: '[0-9]\{4\}-[01][0-9]-[0-3][0-9]T[0-2][0-9]:[0-5][0-9]:[0-5][0-9]\.[0-9]\{3\}Z'|FAMILY_MEMBER_EULA_LAST_CHANGED_DATE: '$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")'|\" ./shared/constants.js" >> dockerfile
            fi

          if [ ! -z "${{ github.event.inputs.lastSupportedVersion }}" ] && [ ! -z "${{ github.event.inputs.serverVersion }}" ]
            then
              echo "RUN sed -i \"s|${{ github.event.inputs.version }}|${{ github.event.inputs.serverVersion }}-build.dev|\" ./fastify-api/package.json" >> dockerfile
              echo "RUN sed -i \"s|LAST_SUPPORTED_VERSION: '[0-9]\.[0-9]\.[0-9]'|LAST_SUPPORTED_VERSION: '${{ github.event.inputs.lastSupportedVersion }}'|\" ./shared/constants.js" >> dockerfile
            fi
          cat dockerfile

      - name: "Push docker release"
        run: |
          az acr login --name vltprodusacr.azurecr.io --subscription 9d434cac-9373-47cc-b022-55009fe50099
          docker build . -t vltprodusacr.azurecr.io/ohana-app-service-api:${{ github.event.inputs.version }}-custom --platform linux/amd64
          docker push vltprodusacr.azurecr.io/ohana-app-service-api:${{ github.event.inputs.version }}-custom
